---
- hosts: all
  become: yes

  vars:
    node_apps_location: /usr/local/opt/node

  pre_tasks:
    - name: update the apt cache if needed
      apt: update_cache=yes cache_valid_time=3600

  tasks:
    - name: Install node js and npm 
      apt:
        state: present
        name: 
          - nodejs
          - npm
    - name: Install forever
      npm: name=forever global=yes state=present
